package main;

enum Asset {CLOSE, FIRE, WATER, EARTH, AIR, DELETE, LAVA, STONE, MUD, PLANT, 
	TREE, WIND, STICK, PICKAXE, HILL, MINE, IRON, AXE, WOOD, MOUNTAINS, 
	BRICKS, HOUSE, VILLAGE, CITY, BALKAN_VILLAGE, LIGHTNING, PERSON, STUPID_PERSON, STUPID_PEOPLE, TROJAN, 
	RESET}
